-- builds luahyperbolic.sty file from lua source files in lua/
-- usage : lua build.lua

local function read(path)
  local f = assert(io.open(path, "r"))
  local s = f:read("*a")
  f:close()
  return s
end

local function write(path, content)
    local f = assert(io.open(path, "w"))
    f:write(content)
    f:close()
end

local function strip_requires(code)
  code = code:gsub("[^\n]*require%s*%b()%s*\n", "")
  return code
end

local function replace_return(code, global_name)
  -- replace final "return m" with global assignment
  -- handles: return m   OR   return   m
  return code:gsub("return%s+m%s*$", global_name .. " = m")
end

local function wrap_module(code)
  return "do\n" .. code .. "\nend\n"
end

local complex_code = read("lua/complex.lua")
complex_code = strip_requires(complex_code)
complex_code = replace_return(complex_code, "complex")
complex_code = wrap_module(complex_code)

-- ---- process luahyperbolic-core.lua ----
-- core is NOT exported globally
local core_code = read("lua/luahyperbolic-core.lua")
core_code = strip_requires(core_code)
core_code = core_code:gsub("return%s+m%s*$", "local core = m")

local tikz_code = read("lua/luahyperbolic-tikz.lua")
tikz_code = strip_requires(tikz_code)
tikz_code = replace_return(tikz_code, "hyper")
tikz_code = wrap_module(tikz_code)

-- ---- concatenate all code ----
local timestamp = os.date("%Y/%m/%d %H:%M:%S")
local all_code = table.concat({
    "-- AUTO-GENERATED FILE\n-- DO NOT EDIT\n\n",
    "-- DATE : " .. timestamp, 
    complex_code,
    core_code,
    tikz_code
}, "\n")

-- do NOT strip comments : caution ! TikZ paths "(x,y) -- (z,t)"

-- for debug :
-- write("lua/bundle[AUTOGENERATED].lua", all_code)
-- print("lua/bundle[AUTOGENERATED].lua written successfully")

local template  = read("lua/luahyperbolic.template.sty")
local final_sty = template:gsub("%-%- ===PLACEHOLDER===", function()
    return all_code
end)

-- backup, optional : 
-- local ok, err = os.rename("luahyperbolic.sty", "backup/luahyperbolic-".. os.date("%Y-%m-%d--%H-%M-%S") ..".sty")
-- if not ok then
--     print("Could not backup luahyperbolic.sty:", err)
--   else
--     print("Backup successful : luahyperbolic.sty")
-- end

write("luahyperbolic.sty", final_sty)
print("luahyperbolic.sty written successfully")

